In [1]:
import pandas as pd
import requests
from google.colab import files

# Upload and Preprocess the Dataset

In [3]:
urls = [
    "http://pin13.net/car2go/data/2012-06.txt.gz",
    "http://pin13.net/car2go/data/2012-07.txt.gz",
    "http://pin13.net/car2go/data/2012-08.txt.gz",
    "http://pin13.net/car2go/data/2012-09.txt.gz",
    "http://pin13.net/car2go/data/2012-10.txt.gz",
    "http://pin13.net/car2go/data/2012-12.txt.gz",
    "http://pin13.net/car2go/data/2013-01.txt.gz",
    "http://pin13.net/car2go/data/2013-02.txt.gz",
    "http://pin13.net/car2go/data/2013-03.txt.gz",
    "http://pin13.net/car2go/data/2013-04.txt.gz",
    "http://pin13.net/car2go/data/2013-05.txt.gz",
    "http://pin13.net/car2go/data/2013-06.txt.gz",
    "http://pin13.net/car2go/data/2013-07.txt.gz",
    "http://pin13.net/car2go/data/2013-08.txt.gz",
    "http://pin13.net/car2go/data/2013-09.txt.gz",
    "http://pin13.net/car2go/data/2013-10.txt.gz",
    "http://pin13.net/car2go/data/2013-11.txt.gz"]

for url in urls:
    filename = url.split('/')[-1]

    response = requests.get(url, stream=True)
    response.raise_for_status()

    with open(filename, 'wb') as file:
        for chunk in response.iter_content(chunk_size=8192):
            file.write(chunk)

    print(f"File {filename} downloaded successfully!")

File 2012-06.txt.gz downloaded successfully!
File 2012-07.txt.gz downloaded successfully!
File 2012-08.txt.gz downloaded successfully!
File 2012-09.txt.gz downloaded successfully!
File 2012-10.txt.gz downloaded successfully!
File 2012-12.txt.gz downloaded successfully!
File 2013-01.txt.gz downloaded successfully!
File 2013-02.txt.gz downloaded successfully!
File 2013-03.txt.gz downloaded successfully!
File 2013-04.txt.gz downloaded successfully!
File 2013-05.txt.gz downloaded successfully!
File 2013-06.txt.gz downloaded successfully!
File 2013-07.txt.gz downloaded successfully!
File 2013-08.txt.gz downloaded successfully!
File 2013-09.txt.gz downloaded successfully!
File 2013-10.txt.gz downloaded successfully!
File 2013-11.txt.gz downloaded successfully!

In [4]:
#combine the dataset
filenames = ["2012-06.txt.gz"]

#filenames = [
    #"2012-06.txt.gz",
    #"2012-07.txt.gz"
   # ]

Data = pd.concat([pd.read_csv(f) for f in filenames],ignore_index=True)

In [5]:
print(Data.shape)

(582304, 7)

In [6]:
Data.head()

,date,license,latitude,longitude,fuel,interior,exterior
0,2012-06-01 20:58:56,191FRH,45.471205,-122.648474,100,true,true
1,2012-06-01 20:58:56,158FRH,45.558546,-122.709414,87,true,true
2,2012-06-01 20:58:56,192FRH,45.515036,-122.629782,54,true,true
3,2012-06-01 20:58:56,196FRH,45.554366,-122.671270,100,true,true
4,2012-06-01 20:58:56,197FRH,45.562482,-122.632860,48,true,true

Found there are leading spaces in the names of the columns and the values, then we get rid of the spaces

In [7]:
Data.columns = [col.strip() for col in Data.columns]  #get rid of the leading space in the name of coulmns

In [8]:
variable_names = Data.columns.tolist()
variable_names #check whether the names of columns are okay

['date', 'license', 'latitude', 'longitude', 'fuel', 'interior', 'exterior']

In [9]:
Data = Data.applymap(lambda x: x.strip() if isinstance(x, str) else x) #get rid of the leading space in the values

Separate the date and time

In [10]:
#sperate the Real date and time
Data['time'] = pd.to_datetime(Data['date']).dt.time
Data['date'] = pd.to_datetime(Data['date']).dt.date

In [11]:
#adjust the order of columns
desired_order = ['license', 'date', 'time', 'latitude', 'longitude', 'fuel', 'interior', 'exterior',]
Data = Data[desired_order]

In [12]:
Data.head(100)

,license,date,time,latitude,longitude,fuel,interior,exterior
0,191FRH,2012-06-01,20:58:56,45.471205,-122.648474,100,true,true
1,158FRH,2012-06-01,20:58:56,45.558546,-122.709414,87,true,true
2,192FRH,2012-06-01,20:58:56,45.515036,-122.629782,54,true,true
3,196FRH,2012-06-01,20:58:56,45.554366,-122.671270,100,true,true
4,197FRH,2012-06-01,20:58:56,45.562482,-122.632860,48,true,true
...,...,...,...,...,...,...,...,...
95,238FRH,2012-06-01,20:58:56,45.511086,-122.653625,78,true,true
96,237FRH,2012-06-01,20:58:56,45.516997,-122.593723,54,false,true
97,236FRH,2012-06-01,20:58:56,45.523839,-122.659648,66,true,true
98,216FRH,2012-06-01,20:58:56,45.518549,-122.627328,21,true,true
99,235FRH,2012-06-01,20:58:56,45.542560,-122.672048,21,true,true

Change the results in interior and exterior to catergorical number

In [13]:
# Convert true and false to 1 and 0, notice that is string not boolean
for col in ['interior','exterior']:
    Data[col] = Data[col].replace({'true': 1, 'false': 0})

In [14]:
Data.head(100)

,license,date,time,latitude,longitude,fuel,interior,exterior
0,191FRH,2012-06-01,20:58:56,45.471205,-122.648474,100,1,1
1,158FRH,2012-06-01,20:58:56,45.558546,-122.709414,87,1,1
2,192FRH,2012-06-01,20:58:56,45.515036,-122.629782,54,1,1
3,196FRH,2012-06-01,20:58:56,45.554366,-122.671270,100,1,1
4,197FRH,2012-06-01,20:58:56,45.562482,-122.632860,48,1,1
...,...,...,...,...,...,...,...,...
95,238FRH,2012-06-01,20:58:56,45.511086,-122.653625,78,1,1
96,237FRH,2012-06-01,20:58:56,45.516997,-122.593723,54,0,1
97,236FRH,2012-06-01,20:58:56,45.523839,-122.659648,66,1,1
98,216FRH,2012-06-01,20:58:56,45.518549,-122.627328,21,1,1
99,235FRH,2012-06-01,20:58:56,45.542560,-122.672048,21,1,1

# Locate the Renting Timepoint

For each vehicle, abs delta latitude >= 0.01 AND abs delta longitude >= 0.01 AND fuel decrease

Notes: The location/latitude/longitude would change which getting charged, so we should care whether the battery level decrease

In [15]:
#to check the number of vehicles we are going to track
#num_vehicle= Data['license'].nunique()
#print(num_vehicle)  #The number of vehicles is not exactly as what they said 316 ALWAYS

In [16]:
#unique_vehicle =Data['license'].unique()
#print(unique_vehicle)

In [17]:
#convert the numpy.ndarray to a list
#unique_vehicle_list = unique_vehicle.tolist()

#print(type(unique_vehicle_list))

Sort the records

In [18]:
Data.sort_values(by=['license', 'date', 'time'], inplace=True) #sort the records as license, date and time

In [19]:
Data.reset_index(drop=True, inplace=True)#set the new index

In [20]:
#Data.to_csv('cleaned_data.csv', index=False)
#files.download('cleaned_data.csv')

Set the difference

In [21]:
# Calculate the difference between consecutive rows for 'latitude', 'longitude', and 'fuel'
Data['latitude_diff'] = Data['latitude'].diff()
Data['longitude_diff'] = Data['longitude'].diff()
Data['fuel_diff'] = Data['fuel'].diff()

filter = (Data['latitude_diff'] != 0) & (Data['longitude_diff'] != 0) & (Data['fuel_diff'] <= 0)

In [27]:
print(len(Data[filter])) #check the number of pick-up

17005

Set the two consecutive rows

In [22]:
collection_set = filter | filter.shift(-1) #combine the needed rows

Data_collection= Data[collection_set]
Data_collection = Data_collection.drop(['latitude_diff', 'longitude_diff', 'fuel_diff'], axis=1)

In [23]:
print(Data_collection.head(30))

    license        date      time   latitude   longitude  fuel  interior  \
0    151FRH  2012-06-01  20:58:56  45.510180 -122.675216    33         1
1    151FRH  2012-06-01  22:58:03  45.514420 -122.654003    33         1
10   151FRH  2012-06-02  01:15:02  45.514420 -122.654003    33         1
11   151FRH  2012-06-02  01:45:03  45.533480 -122.604074    30         0
134  151FRH  2012-06-03  10:45:02  45.523880 -122.650722   100         1
135  151FRH  2012-06-03  11:15:03  45.523861 -122.698368   100         1
156  151FRH  2012-06-03  16:30:03  45.523861 -122.698368   100         1
157  151FRH  2012-06-03  16:45:03  45.524908 -122.689948   100         1
164  151FRH  2012-06-03  18:30:03  45.524908 -122.689948   100         1
165  151FRH  2012-06-03  19:15:03  45.559033 -122.644220   100         1
171  151FRH  2012-06-03  20:45:03  45.559033 -122.644220   100         1
172  151FRH  2012-06-03  21:45:03  45.522510 -122.689915   100         1
215  151FRH  2012-06-04  08:30:04  45.522510 -122.689915   100         1
216  151FRH  2012-06-04  09:00:04  45.518857 -122.683832   100         1
228  151FRH  2012-06-04  12:00:05  45.518857 -122.683832   100         1
229  151FRH  2012-06-04  12:30:03  45.531230 -122.652590   100         1
241  151FRH  2012-06-04  15:30:04  45.531230 -122.652590   100         1
242  151FRH  2012-06-04  16:00:04  45.523530 -122.688528   100         1
246  151FRH  2012-06-04  17:00:03  45.523530 -122.688528   100         1
247  151FRH  2012-06-04  17:30:03  45.526375 -122.685833   100         1
249  151FRH  2012-06-04  18:00:03  45.526375 -122.685833   100         1
250  151FRH  2012-06-04  18:30:04  45.536524 -122.648383   100         1
352  151FRH  2012-06-05  20:00:04  45.536524 -122.648383   100         1
353  151FRH  2012-06-05  20:30:04  45.520845 -122.682392   100         1
360  151FRH  2012-06-05  22:15:03  45.520845 -122.682392   100         1
361  151FRH  2012-06-05  23:00:05  45.508702 -122.681880   100         1
367  151FRH  2012-06-06  00:30:03  45.508702 -122.681880   100         1
368  151FRH  2012-06-06  01:00:04  45.495214 -122.670797   100         1
393  151FRH  2012-06-06  07:15:07  45.495214 -122.670797   100         1
394  151FRH  2012-06-06  08:00:04  45.523247 -122.683151   100         1

     exterior
0           1
1           1
10          1
11          0
134         1
135         1
156         1
157         1
164         1
165         1
171         1
172         1
215         1
216         1
228         1
229         1
241         1
242         1
246         1
247         1
249         1
250         1
352         1
353         1
360         1
361         1
367         1
368         1
393         1
394         1

Add the another column to distinguish, setting the former one as 1, the latter one as 2

In [28]:
Data_collection_new= Data[collection_set]
Data_collection_new['group'] = None

#setting original filter as 2
Data_collection_new.loc[filter, 'group'] = 2
#shift back one row, setting as 1
shift_filter = (Data_collection_new['group'].shift(-1) == 2) & collection_set
Data_collection_new.loc[shift_filter, 'group'] = 1

# Drop the diff columns if no longer needed
Data_collection_new = Data_collection_new.drop(['latitude_diff', 'longitude_diff', 'fuel_diff'], axis=1)

# Display the head of the DataFrame
print(Data_collection_new.head(35))

<ipython-input-28-3dc695e52840>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_collection_new['group'] = None

    license        date      time   latitude   longitude  fuel  interior  \
0    151FRH  2012-06-01  20:58:56  45.510180 -122.675216    33         1
1    151FRH  2012-06-01  22:58:03  45.514420 -122.654003    33         1
10   151FRH  2012-06-02  01:15:02  45.514420 -122.654003    33         1
11   151FRH  2012-06-02  01:45:03  45.533480 -122.604074    30         0
134  151FRH  2012-06-03  10:45:02  45.523880 -122.650722   100         1
135  151FRH  2012-06-03  11:15:03  45.523861 -122.698368   100         1
156  151FRH  2012-06-03  16:30:03  45.523861 -122.698368   100         1
157  151FRH  2012-06-03  16:45:03  45.524908 -122.689948   100         1
164  151FRH  2012-06-03  18:30:03  45.524908 -122.689948   100         1
165  151FRH  2012-06-03  19:15:03  45.559033 -122.644220   100         1
171  151FRH  2012-06-03  20:45:03  45.559033 -122.644220   100         1
172  151FRH  2012-06-03  21:45:03  45.522510 -122.689915   100         1
215  151FRH  2012-06-04  08:30:04  45.522510 -122.689915   100         1
216  151FRH  2012-06-04  09:00:04  45.518857 -122.683832   100         1
228  151FRH  2012-06-04  12:00:05  45.518857 -122.683832   100         1
229  151FRH  2012-06-04  12:30:03  45.531230 -122.652590   100         1
241  151FRH  2012-06-04  15:30:04  45.531230 -122.652590   100         1
242  151FRH  2012-06-04  16:00:04  45.523530 -122.688528   100         1
246  151FRH  2012-06-04  17:00:03  45.523530 -122.688528   100         1
247  151FRH  2012-06-04  17:30:03  45.526375 -122.685833   100         1
249  151FRH  2012-06-04  18:00:03  45.526375 -122.685833   100         1
250  151FRH  2012-06-04  18:30:04  45.536524 -122.648383   100         1
352  151FRH  2012-06-05  20:00:04  45.536524 -122.648383   100         1
353  151FRH  2012-06-05  20:30:04  45.520845 -122.682392   100         1
360  151FRH  2012-06-05  22:15:03  45.520845 -122.682392   100         1
361  151FRH  2012-06-05  23:00:05  45.508702 -122.681880   100         1
367  151FRH  2012-06-06  00:30:03  45.508702 -122.681880   100         1
368  151FRH  2012-06-06  01:00:04  45.495214 -122.670797   100         1
393  151FRH  2012-06-06  07:15:07  45.495214 -122.670797   100         1
394  151FRH  2012-06-06  08:00:04  45.523247 -122.683151   100         1
395  151FRH  2012-06-06  09:15:03  45.521530 -122.679702    93         1
404  151FRH  2012-06-06  11:30:04  45.521530 -122.679702    93         1
405  151FRH  2012-06-06  11:45:03  45.531282 -122.682412    93         1
409  151FRH  2012-06-06  12:45:03  45.531282 -122.682412    93         1
410  151FRH  2012-06-06  13:30:04  45.531285 -122.682288    93         1

     exterior group
0           1     1
1           1     2
10          1     1
11          0     2
134         1     1
135         1     2
156         1     1
157         1     2
164         1     1
165         1     2
171         1     1
172         1     2
215         1     1
216         1     2
228         1     1
229         1     2
241         1     1
242         1     2
246         1     1
247         1     2
249         1     1
250         1     2
352         1     1
353         1     2
360         1     1
361         1     2
367         1     1
368         1     2
393         1     1
394         1     1
395         1     2
404         1     1
405         1     2
409         1     1
410         1     2

Check the duration of trips

In [25]:
# Get the indices of the filtered rows
filter_index = Data.index[filter]

# Create a boolean series
duration_check = pd.Series(False, index=Data.index)

for index in filter_index: #for loop
    if index + 1 < len(Data): # within the range
           if Data.at[index, 'longitude'] != Data.at[index + 1, 'longitude']:  # Check whether the difference in longitude is non-zero, only needed to do once, the results of latitude must be same
               duration_check.at[index] = True

check_rows = Data[duration_check]

In [26]:
print(check_rows)

       license        date      time   latitude   longitude  fuel  interior  \
394     151FRH  2012-06-06  08:00:04  45.523247 -122.683151   100         1
566     151FRH  2012-06-08  09:45:03  45.501558 -122.678208    57         1
588     151FRH  2012-06-08  16:00:04  45.555330 -122.679818    51         1
840     151FRH  2012-06-11  21:30:03  45.533939 -122.634460    30         1
2110    151FRH  2012-06-26  17:30:04  45.512006 -122.642848    57         1
...        ...         ...       ...        ...         ...   ...       ...
580957  511FSK  2012-06-15  17:30:06  45.527809 -122.686439    81         1
581226  511FSK  2012-06-18  17:15:05  45.515703 -122.627546    60         1
581321  511FSK  2012-06-19  18:15:04  45.534460 -122.635414    54         1
581667  511FSK  2012-06-23  14:15:04  45.519252 -122.610942   100         1
581674  511FSK  2012-06-23  16:30:06  45.533025 -122.636767   100         1

        exterior  latitude_diff  longitude_diff  fuel_diff
394            1       0.028033       -0.012354        0.0
566            1      -0.053236        0.001582       -3.0
588            1       0.029057        0.015015       -3.0
840            1       0.000367        0.019890        0.0
2110           1      -0.004893        0.032431        0.0
...          ...            ...             ...        ...
580957         1      -0.003615       -0.003164        0.0
581226         1      -0.010819        0.008625        0.0
581321         1       0.002259        0.008258        0.0
581667         1      -0.007629        0.049680        0.0
581674         1       0.009379        0.009629        0.0

[1691 rows x 11 columns]