In [7]:
import pandas as pd
import requests

# Upload the Dataset

In [4]:
urls = [
    "http://pin13.net/car2go/data/2012-06.txt.gz",
    "http://pin13.net/car2go/data/2012-07.txt.gz",
    "http://pin13.net/car2go/data/2012-08.txt.gz",
    "http://pin13.net/car2go/data/2012-09.txt.gz",
    "http://pin13.net/car2go/data/2012-10.txt.gz",
    "http://pin13.net/car2go/data/2012-12.txt.gz",
    "http://pin13.net/car2go/data/2013-01.txt.gz",
    "http://pin13.net/car2go/data/2013-02.txt.gz",
    "http://pin13.net/car2go/data/2013-03.txt.gz",
    "http://pin13.net/car2go/data/2013-04.txt.gz",
    "http://pin13.net/car2go/data/2013-05.txt.gz",
    "http://pin13.net/car2go/data/2013-06.txt.gz",
    "http://pin13.net/car2go/data/2013-07.txt.gz",
    "http://pin13.net/car2go/data/2013-08.txt.gz",
    "http://pin13.net/car2go/data/2013-09.txt.gz",
    "http://pin13.net/car2go/data/2013-10.txt.gz",
    "http://pin13.net/car2go/data/2013-11.txt.gz"]

for url in urls:
    filename = url.split('/')[-1]

    response = requests.get(url, stream=True)
    response.raise_for_status()

    with open(filename, 'wb') as file:
        for chunk in response.iter_content(chunk_size=8192):
            file.write(chunk)

    print(f"File {filename} downloaded successfully!")

File 2012-06.txt.gz downloaded successfully!
File 2012-07.txt.gz downloaded successfully!
File 2012-08.txt.gz downloaded successfully!
File 2012-09.txt.gz downloaded successfully!
File 2012-10.txt.gz downloaded successfully!
File 2012-12.txt.gz downloaded successfully!
File 2013-01.txt.gz downloaded successfully!
File 2013-02.txt.gz downloaded successfully!
File 2013-03.txt.gz downloaded successfully!
File 2013-04.txt.gz downloaded successfully!
File 2013-05.txt.gz downloaded successfully!
File 2013-06.txt.gz downloaded successfully!
File 2013-07.txt.gz downloaded successfully!
File 2013-08.txt.gz downloaded successfully!
File 2013-09.txt.gz downloaded successfully!
File 2013-10.txt.gz downloaded successfully!
File 2013-11.txt.gz downloaded successfully!

In [86]:
#combine the dataset
filenames = ["2012-06.txt.gz","2012-07.txt.gz","2012-08.txt.gz","2012-09.txt.gz", "2012-10.txt.gz"]

#filenames = [
    #"2012-06.txt.gz",
    #"2012-07.txt.gz"
   # ]

Data = pd.concat([pd.read_csv(f) for f in filenames],ignore_index=True)

In [62]:
print(Data.shape)

(2823086, 7)

In [87]:
Data.head()

,date,license,latitude,longitude,fuel,interior,exterior
0,2012-06-01 20:58:56,191FRH,45.471205,-122.648474,100,true,true
1,2012-06-01 20:58:56,158FRH,45.558546,-122.709414,87,true,true
2,2012-06-01 20:58:56,192FRH,45.515036,-122.629782,54,true,true
3,2012-06-01 20:58:56,196FRH,45.554366,-122.671270,100,true,true
4,2012-06-01 20:58:56,197FRH,45.562482,-122.632860,48,true,true

In [88]:
Data.columns = [col.strip() for col in Data.columns]  #get rid of the leading space in the name of coulmns

In [89]:
variable_names = Data.columns.tolist()
variable_names

['date', 'license', 'latitude', 'longitude', 'fuel', 'interior', 'exterior']

In [90]:
Data = Data.applymap(lambda x: x.strip() if isinstance(x, str) else x) #get rid of the leading space in the values

In [91]:
#sperate the Real date and time
Data['date_1'] = pd.to_datetime(Data['date']).dt.date
Data['time'] = pd.to_datetime(Data['date']).dt.time

In [93]:
Data.head(100)

,date,license,latitude,longitude,fuel,interior,exterior,date_1,time
0,2012-06-01 20:58:56,191FRH,45.471205,-122.648474,100,true,true,2012-06-01,20:58:56
1,2012-06-01 20:58:56,158FRH,45.558546,-122.709414,87,true,true,2012-06-01,20:58:56
2,2012-06-01 20:58:56,192FRH,45.515036,-122.629782,54,true,true,2012-06-01,20:58:56
3,2012-06-01 20:58:56,196FRH,45.554366,-122.671270,100,true,true,2012-06-01,20:58:56
4,2012-06-01 20:58:56,197FRH,45.562482,-122.632860,48,true,true,2012-06-01,20:58:56
...,...,...,...,...,...,...,...,...,...
95,2012-06-01 20:58:56,238FRH,45.511086,-122.653625,78,true,true,2012-06-01,20:58:56
96,2012-06-01 20:58:56,237FRH,45.516997,-122.593723,54,false,true,2012-06-01,20:58:56
97,2012-06-01 20:58:56,236FRH,45.523839,-122.659648,66,true,true,2012-06-01,20:58:56
98,2012-06-01 20:58:56,216FRH,45.518549,-122.627328,21,true,true,2012-06-01,20:58:56
99,2012-06-01 20:58:56,235FRH,45.542560,-122.672048,21,true,true,2012-06-01,20:58:56

In [100]:
# Convert true and false to 1 and 0, notice that is string not boolean
for col in ['interior','exterior']:
    Data[col] = Data[col].replace({'true': 1, 'false': 0})

In [101]:
Data.head(100)

,date,license,latitude,longitude,fuel,interior,exterior,date_1,time
0,2012-06-01 20:58:56,191FRH,45.471205,-122.648474,100,1,1,2012-06-01,20:58:56
1,2012-06-01 20:58:56,158FRH,45.558546,-122.709414,87,1,1,2012-06-01,20:58:56
2,2012-06-01 20:58:56,192FRH,45.515036,-122.629782,54,1,1,2012-06-01,20:58:56
3,2012-06-01 20:58:56,196FRH,45.554366,-122.671270,100,1,1,2012-06-01,20:58:56
4,2012-06-01 20:58:56,197FRH,45.562482,-122.632860,48,1,1,2012-06-01,20:58:56
...,...,...,...,...,...,...,...,...,...
95,2012-06-01 20:58:56,238FRH,45.511086,-122.653625,78,1,1,2012-06-01,20:58:56
96,2012-06-01 20:58:56,237FRH,45.516997,-122.593723,54,0,1,2012-06-01,20:58:56
97,2012-06-01 20:58:56,236FRH,45.523839,-122.659648,66,1,1,2012-06-01,20:58:56
98,2012-06-01 20:58:56,216FRH,45.518549,-122.627328,21,1,1,2012-06-01,20:58:56
99,2012-06-01 20:58:56,235FRH,45.542560,-122.672048,21,1,1,2012-06-01,20:58:56

# Locate the Renting Timepoint

For each vehicle, abs delta latitude >= 0.01 AND abs delta longitude >= 0.01 AND fuel decrease

Notes: The location/latitude/longitude would change which getting charged, so we should care whether the battery level decrease

In [102]:
#to check the number of vehicles we are going to track
num_vehicle= Data['license'].nunique()
print(num_vehicle)  #The number of vehicles is not exactly as what they said 316 ALWAYS

276

In [103]:
unique_vehicle =Data['license'].unique()
print(unique_vehicle)

['191FRH' '158FRH' '192FRH' '196FRH' '197FRH' '198FRH' '199FRH' '200FRH'
 '168FRH' '337FRH' '336FRH' '334FRH' '333FRH' '332FRH' '328FRH' '166FRH'
 '173FRH' '156FRH' '155FRH' '154FRH' '330FRH' '327FRH' '153FRH' '329FRH'
 '325FRH' '324FRH' '152FRH' '151FRH' '251FRH' '252FRH' '253FRH' '254FRH'
 '255FRH' '256FRH' '259FRH' '260FRH' '261FRH' '264FRH' '265FRH' '266FRH'
 '270FRH' '269FRH' '268FRH' '267FRH' '319FRH' '318FRH' '316FRH' '315FRH'
 '314FRH' '313FRH' '310FRH' '163FRH' '309FRH' '308FRH' '307FRH' '306FRH'
 '305FRH' '304FRH' '302FRH' '301FRH' '227FRH' '209FRH' '160FRH' '208FRH'
 '207FRH' '170FRH' '225FRH' '224FRH' '223FRH' '222FRH' '164FRH' '221FRH'
 '220FRH' '219FRH' '218FRH' '217FRH' '230FRH' '229FRH' '211FRH' '206FRH'
 '228FRH' '250FRH' '249FRH' '248FRH' '175FRH' '241FRH' '161FRH' '215FRH'
 '246FRH' '174FRH' '245FRH' '244FRH' '243FRH' '240FRH' '239FRH' '238FRH'
 '237FRH' '236FRH' '216FRH' '235FRH' '234FRH' '233FRH' '232FRH' '231FRH'
 '176FRH' '177FRH' '178FRH' '180FRH' '181FRH' '210FRH' '184FRH' '212FRH'
 '338FRH' '185FRH' '186FRH' '202FRH' '201FRH' '203FRH' '320FRH' '321FRH'
 '322FRH' '323FRH' '346FRH' '345FRH' '167FRH' '343FRH' '342FRH' '341FRH'
 '339FRH' '187FRH' '189FRH' '190FRH' '172FRH' '381FRH' '383FRH' '384FRH'
 '385FRH' '386FRH' '387FRH' '350FRH' '388FRH' '391FRH' '392FRH' '393FRH'
 '394FRH' '395FRH' '396FRH' '397FRH' '399FRH' '400FRH' '348FRH' '361FRH'
 '362FRH' '364FRH' '363FRH' '365FRH' '366FRH' '367FRH' '368FRH' '371FRH'
 '372FRH' '374FRH' '376FRH' '377FRH' '378FRH' '380FRH' '274FRH' '282FRH'
 '300FRH' '359FRH' '354FRH' '285FRH' '294FRH' '288FRH' '356FRH' '298FRH'
 '284FRH' '299FRH' '273FRH' '286FRH' '272FRH' '292FRH' '289FRH' '279FRH'
 '382FRH' '295FRH' '283FRH' '352FRH' '293FRH' '355FRH' '357FRH' '353FRH'
 '291FRH' '335FRH' '326FRH' '169FRH' '347FRH' '390FRH' '281FRH' '296FRH'
 '204FRH' '317FRH' '297FRH' '188FRH' '290FRH' '214FRH' '278FRH' '312FRH'
 '379FRH' '226FRH' '179FRH' '247FRH' '511FSK' '195FRH' '194FRH' '344FRH'
 '157FRH' '258FRH' '303FRH' '369FRH' '275FRH' '205FRH' '375FRH' '271FRH'
 '331FRH' '358FRH' '277FRH' '257FRH' '351FRH' '287FRH' '171FRH' '373FRH'
 '340FRH' '510FSK' '311FRH' '182FRH' '360FRH' '389FRH' '370FRH' '162FRH'
 '193FRH' '276FRH' '263FRH' '165FRH' '183FRH' '280FRH' '019FTH' '015FTH'
 '027FTH' '022FTH' '016FTH' '017FTH' '003FTH' '021FTH' '026FTH' '023FTH'
 '010FTH' '012FTH' '011FTH' '009FTH' '001FTH' '024FTH' '030FTH' '007FTH'
 '018FTH' '008FTH' '004FTH' '028FTH' '159FRH' '242FRH' '398FRH' '213FRH'
 '025FTH' '014FTH' '020FTH' '005FTH']

In [104]:
#convert the numpy.ndarray to a list
unique_vehicle_list = unique_vehicle.tolist()

print(type(unique_vehicle_list))

<class 'list'>

In [117]:
#Data = Data.sort_values(by=['license', 'data_1'])
sorted_data = Data.sort_values(by=['license', 'date_1', 'time'])

print(sorted_data)

                        date license   latitude   longitude  fuel  interior  \
1611679  2012-08-23 16:30:08  001FTH  45.511938 -122.683316    52         1
1611881  2012-08-23 16:45:05  001FTH  45.511938 -122.683316    52         1
1612072  2012-08-23 17:00:10  001FTH  45.511938 -122.683316    52         1
1612263  2012-08-23 17:15:05  001FTH  45.511938 -122.683316    52         1
1612641  2012-08-23 17:45:06  001FTH  45.511938 -122.683316    52         1
...                      ...     ...        ...         ...   ...       ...
2822118  2012-10-19 05:00:09  511FSK  45.539137 -122.697080   100         1
2822354  2012-10-19 05:15:07  511FSK  45.539137 -122.697080   100         1
2822588  2012-10-19 05:30:08  511FSK  45.539137 -122.697080   100         1
2822821  2012-10-19 05:45:05  511FSK  45.539137 -122.697080   100         1
2823053  2012-10-19 06:00:10  511FSK  45.539137 -122.697080   100         1

         exterior      date_1      time  longitude_diff  battery_diff
1611679         1  2012-08-23  16:30:08             NaN           NaN
1611881         1  2012-08-23  16:45:05             0.0           0.0
1612072         1  2012-08-23  17:00:10             0.0           0.0
1612263         1  2012-08-23  17:15:05             0.0           0.0
1612641         1  2012-08-23  17:45:06             0.0           0.0
...           ...         ...       ...             ...           ...
2822118         1  2012-10-19  05:00:09             0.0           0.0
2822354         1  2012-10-19  05:15:07             0.0           0.0
2822588         1  2012-10-19  05:30:08             0.0           0.0
2822821         1  2012-10-19  05:45:05             0.0           0.0
2823053         1  2012-10-19  06:00:10             0.0           0.0

[2823086 rows x 11 columns]

In [120]:
sorted_data['longitude_diff'] = sorted_data.groupby('license')['longitude'].diff()
sorted_data['battery_diff'] = sorted_data.groupby('license')['fuel'].diff()

In [121]:
sorted_data.head(1000)

,date,license,latitude,longitude,fuel,interior,exterior,date_1,time,longitude_diff,battery_diff
1611679,2012-08-23 16:30:08,001FTH,45.511938,-122.683316,52,1,1,2012-08-23,16:30:08,NaN,NaN
1611881,2012-08-23 16:45:05,001FTH,45.511938,-122.683316,52,1,1,2012-08-23,16:45:05,0.000000,0.0
1612072,2012-08-23 17:00:10,001FTH,45.511938,-122.683316,52,1,1,2012-08-23,17:00:10,0.000000,0.0
1612263,2012-08-23 17:15:05,001FTH,45.511938,-122.683316,52,1,1,2012-08-23,17:15:05,0.000000,0.0
1612641,2012-08-23 17:45:06,001FTH,45.511938,-122.683316,52,1,1,2012-08-23,17:45:06,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2100959,2012-09-15 16:15:05,001FTH,45.526314,-122.682748,81,1,1,2012-09-15,16:15:05,0.000000,0.0
2101167,2012-09-15 16:30:07,001FTH,45.526314,-122.682748,81,1,1,2012-09-15,16:30:07,0.000000,0.0
2101601,2012-09-15 17:00:08,001FTH,45.526498,-122.682926,96,1,1,2012-09-15,17:00:08,-0.000178,15.0
2101811,2012-09-15 17:15:05,001FTH,45.526498,-122.682926,96,1,1,2012-09-15,17:15:05,0.000000,0.0
2102452,2012-09-15 18:00:10,001FTH,45.502675,-122.622921,92,1,1,2012-09-15,18:00:10,0.060005,-4.0

In [123]:
count = (sorted_data['longitude_diff'] != 0) & (~sorted_data['longitude_diff'].isnull())

print(count.sum())

101728

In [115]:
count = len(Data['longitude'].dropna()[Data['longitude'].dropna() != 0])

print(count)

2823086

In [110]:
filtered_data = Data[(Data['longitude_diff'].abs() > 0.001) & (Data['battery_diff'] < 0)]